[package]
name = "tagmap"
version = "0.1.0"
edition = "2021"
autoexamples = false

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
anyhow = "1.0.86"
lazy_static = "1.5.0"
paste = "1.0.15"
tempfile = "3.10.1"
